curl 'https://api2.cryptoslam.io/api/sales/NBA%20Top%20Shot/search' \
  -H 'authority: api2.cryptoslam.io' \
  -H 'sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"' \
  -H 'accept: application/json, text/javascript, */*; q=0.01' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36' \
  -H 'token: 0HO4P3zZ3BfxgWA0OIHRlvvVqmWkX6Fj5PJxACA+UONulQu+HWHMr07tQ6ShW/Yhr6S9PHJ69IcFpAu1cAKQaOBCSgbtJJjnec4QHiVOspEdBUCc0vd06mdvI16A5X2V3Vj99X1hQK/5jFweMyVvE0juNqcrUITgw+Kd+TUk9bgV9qaSIkDigWDRo2/2Jhg0utGL+iz/0+5fHJuBjp3gbGayIuIXy/e6dD98kP5Zb7KQb5Hy4DdTWRIMn/4UqGFFOxWjBbqePWpw7yWXMYeAN31XpZS/butiOmHPf3IFmaqT0JfwRp5EXuaaji5j3rJ+WMSr7fiWDZoispO9VrY+jA==' \
  -H 'content-type: application/json' \
  -H 'origin: https://www.cryptoslam.io' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://www.cryptoslam.io/' \
  -H 'accept-language: en-US,en;q=0.9' \
  --data-raw '{"draw":6,"columns":[{"data":null,"name":"","searchable":true,"orderable":false,"search":{"value":"","regex":false}},{"data":null,"name":"TimeStamp","searchable":true,"orderable":true,"search":{"value":"","regex":false}},{"data":null,"name":"","searchable":true,"orderable":true,"search":{"value":"","regex":false}},{"data":null,"name":"","searchable":true,"orderable":true,"search":{"value":"","regex":false}},{"data":null,"name":"Tokens.Attributes.Set","searchable":true,"orderable":false,"search":{"value":"","regex":false}},{"data":null,"name":"Tokens.Attributes.Team","searchable":true,"orderable":false,"search":{"value":"","regex":false}},{"data":null,"name":"Tokens.Attributes.PlayCategory","searchable":true,"orderable":false,"search":{"value":"","regex":false}},{"data":null,"name":"Price","searchable":true,"orderable":true,"search":{"value":"","regex":false}},{"data":null,"name":"PriceUSDDoubleType","searchable":true,"orderable":true,"search":{"value":"","regex":false}},{"data":null,"name":"Tokens.Attributes.SerialNumber","searchable":true,"orderable":true,"search":{"value":"","regex":false}},{"data":null,"name":"","searchable":true,"orderable":true,"search":{"value":"","regex":false}},{"data":null,"name":"","searchable":true,"orderable":true,"search":{"value":"","regex":false}}],"order":[{"column":1,"dir":"desc"}],"start":10000,"length":50,"search":{"value":"","regex":false},"startDateHeader":"2021-03-26","endDateHeader":"2021-03-27","startPriceUSDHeader":"","endPriceUSDHeader":"","startPriceHeader":"","endPriceHeader":"","buyer":"","seller":"","attributesQuery":{},"name":"","set":"","marketplace":""}' \
  --compressed